(define libnob (ffi-open "./libnob.so"))

(define-macro (c-import scheme-name lib-handle c-name ret-type arg-types . nfixed)
  (let ((func-ptr (gensym)))
    `(begin
       (define ,func-ptr (ffi-sym ,lib-handle ,c-name))
       (define (,scheme-name . args)
         ,(if (null? nfixed)
              `(ffi-call ,func-ptr ',ret-type ',arg-types args)
              `(ffi-call ,func-ptr ',ret-type ',arg-types args ,(car nfixed)))))))

(define build-dir "build")

(c-import cmd-new           libnob "cmd_new"                 pointer ())
(c-import cmd-append        libnob "cmd_append"              void    (pointer string))
(c-import cmd-run           libnob "cmd_run"                 int     (pointer))
(c-import cmd-run-redirect  libnob "cmd_run_redirect"        int     (pointer string))
(c-import cmd-free          libnob "cmd_free"                void    (pointer))
(c-import needs-rebuild     libnob "needs_rebuild"           int     (pointer pointer))
(c-import delete-file       libnob "nob_delete_file"         int     (string))
(c-import mkdir-if-nexist   libnob "nob_mkdir_if_not_exists" int    (string))

(define (read-file-string filename)
  (let ((port (open-input-file filename)))
    (if port
        (let loop ((chars '()) (c (read-char port)))
          (if (eof-object? c)
              (begin
                (close-input-port port)
                (list->string (reverse chars)))
              (if (or (char-whitespace? c) (char=? c #\newline) (char=? c #\return))
                  (loop chars (read-char port))
                  (loop (cons c chars) (read-char port)))))
        "unknown")))

(define (split-string-by-spaces str)
  (let ((len (string-length str)))
    (let loop ((i 0) (word '()) (words '()))
      (if (>= i len)
          (if (null? word)
              (reverse words)
              (reverse (cons (list->string (reverse word)) words)))
          (let ((c (string-ref str i)))
            (if (char-whitespace? c)
                (if (null? word)
                    (loop (+ i 1) '() words)
                    (loop (+ i 1) '() (cons (list->string (reverse word)) words)))
                (loop (+ i 1) (cons c word) words)))))))

(define (cmd-append-flags cmd flags-str)
  (for-each (lambda (flag)
              (if (and (string? flag) (> (string-length flag) 0))
                  (cmd-append cmd flag)))
            (split-string-by-spaces flags-str)))

(define (get-git-hash)
  (let ((cmd      (cmd-new))
        (filepath (string-append build-dir "/" ".git_hash.txt")))
    (cmd-append cmd "git")
    (cmd-append cmd "rev-parse")
    (cmd-append cmd "--short")
    (cmd-append cmd "HEAD")
    (let ((success (cmd-run-redirect cmd filepath)))
      (cmd-free cmd)
      (if (= success 1)
          (let ((hash (read-file-string filepath)))
            (delete-file filepath)
            hash)
          "unknown"))))

(define (get-pkg-config-cflags)
  (let ((cmd (cmd-new))
        (filepath (string-append build-dir "/" ".ffi_cflags.txt")))
    (cmd-append cmd "pkg-config")
    (cmd-append cmd "--cflags")
    (cmd-append cmd "libffi")
    (let ((success (cmd-run-redirect cmd filepath)))
      (cmd-free cmd)
      (if (= success 1)
          (let ((cflags (read-file-string filepath)))
            (delete-file filepath)
            cflags)
          "-I/usr/lib64/libffi/include"))))

(define (get-pkg-config-libs)
  (let ((cmd (cmd-new))
        (filepath (string-append build-dir "/" ".ffi_libs.txt")))
    (cmd-append cmd "pkg-config")
    (cmd-append cmd "--libs")
    (cmd-append cmd "libffi")
    (let ((success (cmd-run-redirect cmd filepath)))
      (cmd-free cmd)
      (if (= success 1)
          (let ((libs (read-file-string filepath)))
            (delete-file filepath)
            libs)
          "-lffi"))))

(define (needs-rebuild? output input)
  (not (= (needs-rebuild output input) 0)))

(define (append-builddir path)
  (string-append build-dir "/" path)
  )

;; --- Build Process ---

(mkdir-if-nexist build-dir)

(display "Starting Scheme-based build using libnob...\n")

(define git-hash (get-git-hash))
(define ffi-cflags (get-pkg-config-cflags))
(define ffi-libs (get-pkg-config-libs))

(format #t "Git Hash: ~A\n" git-hash)
(format #t "libffi CFLAGS: ~A\n" ffi-cflags)
(format #t "libffi LIBS: ~A\n" ffi-libs)

;; 1. Compile s7.o
(if (or (needs-rebuild? (append-builddir "s7.o") "s7/s7.c")
        (needs-rebuild? (append-builddir "s7.o") "s7/s7.h"))
    (begin
      (display "Rebuilding s7.o...\n")
      (let ((cmd (cmd-new)))
        (cmd-append cmd "gcc")
        (cmd-append cmd "-O2")
        (cmd-append cmd "-march=native")
        (cmd-append cmd "-Wall")
        (cmd-append cmd "-c")
        (cmd-append cmd "s7/s7.c")
        (cmd-append cmd "-o")
        (cmd-append cmd (append-builddir "s7.o"))
        (let ((ok (cmd-run cmd)))
          (cmd-free cmd)
          (if (= ok 0) (error "Failed to compile s7.o")))))
    (display "s7.o is up to date.\n"))

;; 2. Compile main.o
(if (needs-rebuild? (append-builddir "main.o") "main.c")
    (begin
      (display "Rebuilding main.o...\n")
      (let ((cmd (cmd-new)))
        (cmd-append cmd "gcc")
        (cmd-append cmd "-O2")
        (cmd-append cmd "-march=native")
        (cmd-append cmd "-Wall")
        (cmd-append-flags cmd ffi-cflags)
        (cmd-append cmd (string-append "-DHASHVER=\"" git-hash "\""))
        (cmd-append cmd "-c")
        (cmd-append cmd "main.c")
        (cmd-append cmd "-o")
        (cmd-append cmd (append-builddir "main.o"))
        (let ((ok (cmd-run cmd)))
          (cmd-free cmd)
          (if (= ok 0) (error "Failed to compile main.o")))))
    (display "main.o is up to date.\n"))

;; 3. Link lext
(if (or (needs-rebuild? (append-builddir "lext") (append-builddir "main.o"))
        (needs-rebuild? (append-builddir "lext") (append-builddir "s7.o")))
    (begin
      (display "Linking lext...\n")
      (let ((cmd (cmd-new)))
        (cmd-append cmd "gcc")
        (cmd-append cmd (append-builddir "main.o"))
        (cmd-append cmd (append-builddir "s7.o"))
        (cmd-append cmd "-o")
        (cmd-append cmd (append-builddir "lext"))
        (cmd-append cmd "-lm")
        (cmd-append cmd "-ldl")
        (cmd-append-flags cmd ffi-libs)
        (let ((ok (cmd-run cmd)))
          (cmd-free cmd)
          (if (= ok 0) (error "Failed to link lext")))))
    (display "lext is up to date.\n"))

(display "Build finished successfully!\n")
