;;;; basic.scm - Ultimate FFI & Dev Stdlib for s7 Scheme FFI
;;;; Ported from Documents/dev/lext-sbcl/basic.lisp

(define libc-basic (ffi-open #f))

;; --- Typed Pointer Wrapper ---
(define (tptr type ptr)
  (cons type ptr))

(define (tptr-type tp)
  (car tp))

(define (tptr-ptr tp)
  (cdr tp))

(define (tptr? x)
  (and (pair? x)
       (c-pointer? (cdr x))))


;; --- Type Translation Matrix ---
(define (translate-ffi-type type)
  (cond
    ((and (pair? type) (eq? (car type) '*))
     'pointer)
    ((and (pair? type) (eq? (car type) 'struct))
     `(struct ,@(map (lambda (field)
                       (if (and (pair? field) (>= (length field) 2))
                           `(,(translate-ffi-type (car field)) ,(cadr field))
                           field))
                     (cdr type))))
    ((and (pair? type) (eq? (car type) 'union))
     `(union ,@(map (lambda (field)
                      (if (and (pair? field) (>= (length field) 2))
                          `(,(translate-ffi-type (car field)) ,(cadr field))
                          field))
                    (cdr type))))
    ((and (pair? type) (eq? (car type) 'array))
     `(array ,(translate-ffi-type (cadr type)) ,(caddr type)))
    (else
     (case type
       ((void) 'void)
       ((int) 'int)
       ((uint) 'uint)
       ((long) 'long)
       ((ulong) 'ulong)
       ((size_t) 'ulong)
       ((char) 'char)
       ((uchar) 'uchar)
       ((float) 'float)
       ((double) 'double)
       ((string) 'string)
       ((pointer) 'pointer)
       ((int8) 'int8)
       ((int16) 'int16)
       ((int32) 'int32)
       ((int64) 'int64)
       ((uint8) 'uint8)
       ((uint16) 'uint16)
       ((uint32) 'uint32)
       ((uint64) 'uint64)
       (else type)))))

;; --- Structs, Unions, Enums Declarators ---
(define-macro (define-c-struct name . fields)
  `(ffi-typedef ',name
                '(struct ,@(map (lambda (f)
                                  `(,(translate-ffi-type (cadr f)) ,(car f)))
                                fields))))

(define-macro (define-c-union name . fields)
  `(ffi-typedef ',name
                '(union ,@(map (lambda (f)
                                 `(,(translate-ffi-type (cadr f)) ,(car f)))
                               fields))))

(define-macro (define-c-enum name . variants)
  (let ((decls '()))
    (let loop ((vars variants) (val 0))
      (if (not (null? vars))
          (let* ((var (car vars))
                 (sym (if (pair? var) (car var) var))
                 (actual-val (if (pair? var) (cadr var) val)))
            (let* ((sym-str (symbol->string sym))
                   (clean-str (if (char=? (string-ref sym-str 0) #\:)
                                  (substring sym-str 1)
                                  sym-str))
                   (clean-sym (string->symbol clean-str)))
              (set! decls (cons `(define ,clean-sym ,actual-val) decls))
              (loop (cdr vars) (+ actual-val 1))))))
    `(begin ,@(reverse decls))))

;; --- FFI Routine Importer ---
(define-macro (c-import scheme-name lib-handle c-name ret-type arg-types . nfixed)
  (let ((translated-ret (translate-ffi-type ret-type))
        (translated-args (map translate-ffi-type arg-types))
        (func-ptr (gensym)))
    `(begin
       (define ,func-ptr (ffi-sym ,lib-handle ,c-name))
       (define (,scheme-name . args)
         ,(if (null? nfixed)
              `(ffi-call ,func-ptr ',translated-ret ',translated-args args)
              `(ffi-call ,func-ptr ',translated-ret ',translated-args args ,(car nfixed)))))))

;; --- Low-Level Memory Helper Functions (from libc) ---
(c-import c-memcpy-raw libc-basic "memcpy" pointer (pointer pointer ulong))
(c-import c-memset-raw libc-basic "memset" pointer (pointer int ulong))

(define (c-memcpy dest src byte-count)
  (c-memcpy-raw (if (tptr? dest) (tptr-ptr dest) dest)
                (if (tptr? src) (tptr-ptr src) src)
                byte-count))

(define (c-memset dest byte-value byte-count)
  (c-memset-raw (if (tptr? dest) (tptr-ptr dest) dest)
                byte-value
                byte-count))

(define (ptr+ tp offset)
  (if (tptr? tp)
      (tptr (tptr-type tp) (integer->c-pointer (+ (c-pointer->integer (tptr-ptr tp)) offset)))
      (integer->c-pointer (+ (c-pointer->integer tp) offset))))

;; --- Memory Math and Layout Metadata ---
(define (resolve-type type)
  (if (symbol? type)
      (let ((pair (assoc type *ffi-types*)))
        (if pair (cdr pair) type))
      type))

(define (c-align-of type)
  (ffi-align (translate-ffi-type type)))

(define (c-align-to offset alignment)
  (if (= alignment 0)
      offset
      (let ((rem (modulo offset alignment)))
        (if (= rem 0)
            offset
            (+ offset (- alignment rem))))))

(define (c-size type)
  (ffi-size (translate-ffi-type type)))

;; --- Ultimate Pointer Navigator (@) and Mutator (c-set!) ---
(define (struct-field-type struct-name field-name)
  (let ((type-desc (resolve-type struct-name)))
    (if (and (pair? type-desc) (eq? (car type-desc) 'struct))
        (let loop ((fields (cdr type-desc)))
          (if (not (null? fields))
              (let ((f (car fields)))
                (if (and (pair? f) (= (length f) 2))
                    (if (eq? (cadr f) field-name)
                        (car f)
                        (loop (cdr fields)))
                    (loop (cdr fields))))
              #f))
        #f)))

(define (struct-field-offset type-desc field-name)
  (let ((resolved (resolve-type type-desc)))
    (if (and (pair? resolved) (eq? (car resolved) 'struct))
        (let ((offset 0))
          (let loop ((fields (cdr resolved)))
            (if (not (null? fields))
                (let* ((f (car fields))
                       (ftype (car f))
                       (fname (cadr f))
                       (falign (c-align-of ftype)))
                  (set! offset (c-align-to offset falign))
                  (if (eq? fname field-name)
                      offset
                      (begin
                        (set! offset (+ offset (c-size ftype)))
                        (loop (cdr fields)))))
                #f)))
        #f)))

(define (struct-field-type-resolved resolved-type field-name)
  (let loop ((fields (cdr resolved-type)))
    (if (not (null? fields))
        (let ((f (car fields)))
          (if (eq? (cadr f) field-name)
              (car f)
              (loop (cdr fields))))
        #f)))

(define (resolve-path ptr type path)
  (if (null? path)
      (cons ptr type)
      (let* ((step (car path))
             (resolved-type (resolve-type type)))
        (cond
          ((number? step)
           (let* ((elem-type (if (and (pair? resolved-type) (eq? (car resolved-type) 'array))
                                 (cadr resolved-type)
                                 resolved-type))
                  (elem-size (c-size elem-type))
                  (offset (* step elem-size)))
             (resolve-path (ptr+ ptr offset) elem-type (cdr path))))
          ((and (pair? resolved-type) (eq? (car resolved-type) 'struct))
           (let ((offset (struct-field-offset resolved-type step))
                 (field-type (struct-field-type-resolved resolved-type step)))
             (if (not offset)
                 (error "Field not found in struct:" step type)
                 (resolve-path (ptr+ ptr offset) field-type (cdr path)))))
          ((and (pair? resolved-type) (eq? (car resolved-type) 'union))
           (let ((field-type (struct-field-type-resolved resolved-type step)))
             (if (not field-type)
                 (error "Field not found in union:" step type)
                 (resolve-path ptr field-type (cdr path)))))
          (else
           (error "Cannot navigate step on primitive type:" step type))))))

(define (bc.deref ptr type . path)
  (let* ((res (resolve-path ptr type path))
         (target-ptr (car res))
         (target-type (cdr res)))
    (ffi-deref target-ptr target-type)))

(define (bc.set! ptr type value . path)
  (let* ((res (resolve-path ptr type path))
         (target-ptr (car res))
         (target-type (cdr res)))
    (ffi-set! target-ptr target-type value)))

(define (string-split str delim)
  (let ((len (string-length str))
        (delim-char (string-ref delim 0)))
    (let loop ((i 0) (curr '()) (res '()))
      (if (= i len)
          (reverse (cons (list->string (reverse curr)) res))
          (let ((c (string-ref str i)))
            (if (char=? c delim-char)
                (loop (+ i 1) '() (cons (list->string (reverse curr)) res))
                (loop (+ i 1) (cons c curr) res)))))))

(define (string->number-or-symbol str)
  (let ((num (string->number str)))
    (if num num (string->symbol str))))

(define (parse-dot-symbol sym)
  (let* ((parts (string-split (symbol->string sym) ".")))
    (map string->number-or-symbol parts)))

(define (bc.addr tp . path)
  (let* ((ptr (tptr-ptr tp))
         (type (tptr-type tp))
         (res (resolve-path ptr type path))
         (target-ptr (car res))
         (target-type (cdr res)))
    (tptr target-type target-ptr)))

(define-macro (bc.@ obj-path)
  (let* ((parsed (parse-dot-symbol obj-path))
         (obj (car parsed))
         (path (cdr parsed)))
    `(bc.deref (tptr-ptr ,obj) (tptr-type ,obj) ,@(map (lambda (p) `',p) path))))

(define-macro (bc.= obj-path value)
  (let* ((parsed (parse-dot-symbol obj-path))
         (obj (car parsed))
         (path (cdr parsed)))
    `(bc.set! (tptr-ptr ,obj) (tptr-type ,obj) ,value ,@(map (lambda (p) `',p) path))))

(define-macro (bc.& obj-path)
  (let* ((parsed (parse-dot-symbol obj-path))
         (obj (car parsed))
         (path (cdr parsed)))
    `(bc.addr ,obj ,@(map (lambda (p) `',p) path))))

;; --- Memory Sandbox Allocation Macros ---
(define-macro (with-heap-alloc var-type . body)
  (let* ((var (car var-type))
         (type (cadr var-type))
         (count (if (= (length var-type) 3) (caddr var-type) #f))
         (size (if count `(* (c-size ',type) ,count) `(c-size ',type)))
         (ptr (gensym)))
    `(let ((,ptr (malloc ,size)))
       (dynamic-wind
         (lambda () #f)
         (lambda ()
           (let ((,var (tptr ',type ,ptr)))
             ,@body))
         (lambda ()
           (free ,ptr))))))

(define-macro (with-alloc . args)
  `(with-heap-alloc ,@args))

(define-macro (with-c-string var-str . body)
  (let ((var (car var-str))
        (str-expr (cadr var-str))
        (str (gensym))
        (len (gensym))
        (ptr (gensym)))
    `(let* ((,str ,str-expr)
            (,len (string-length ,str))
            (,ptr (malloc (+ ,len 1))))
       (let loop ((i 0))
         (if (< i ,len)
             (begin
               (ffi-set! (ptr+ ,ptr i) 'char (char->integer (string-ref ,str i)))
               (loop (+ i 1)))))
       (ffi-set! (ptr+ ,ptr ,len) 'char 0)
       (dynamic-wind
         (lambda () #f)
         (lambda ()
           (let ((,var (tptr 'char ,ptr)))
             ,@body))
         (lambda ()
           (free ,ptr))))))

(define-macro (with-c-array var-type-list . body)
  (let ((var (car var-type-list))
        (type (cadr var-type-list))
        (lst-expr (caddr var-type-list))
        (lst (gensym))
        (len (gensym))
        (ptr (gensym))
        (size (gensym)))
    `(let* ((,lst ,lst-expr)
            (,len (length ,lst))
            (,size (c-size ',type))
            (,ptr (malloc (* ,len ,size))))
       (let loop ((curr ,lst) (i 0))
         (if (not (null? curr))
             (begin
               (ffi-set! (ptr+ ,ptr (* i ,size)) ',type (car curr))
               (loop (cdr curr) (+ i 1)))))
       (dynamic-wind
         (lambda () #f)
         (lambda ()
           (let ((,var (tptr ',type ,ptr)))
             ,@body))
         (lambda ()
           (free ,ptr))))))

(define-macro (with-c-string-array var-lst . body)
  (let ((var (car var-lst))
        (lst-expr (cadr var-lst))
        (lst (gensym))
        (len (gensym))
        (ptr (gensym))
        (ptrs (gensym))
        (psize (gensym)))
    `(let* ((,lst ,lst-expr)
            (,len (length ,lst))
            (,psize (c-size 'pointer))
            (,ptr (malloc (* (+ ,len 1) ,psize)))
            (,ptrs '()))
       (let loop ((curr ,lst) (i 0))
         (if (not (null? curr))
             (let* ((str (car curr))
                    (slen (string-length str))
                    (sptr (malloc (+ slen 1))))
               (let str-loop ((j 0))
                 (if (< j slen)
                     (begin
                       (ffi-set! (ptr+ sptr j) 'char (char->integer (string-ref str j)))
                       (str-loop (+ j 1)))))
               (ffi-set! (ptr+ sptr slen) 'char 0)
               (ffi-set! (ptr+ ,ptr (* i ,psize)) 'pointer sptr)
               (set! ,ptrs (cons sptr ,ptrs))
               (loop (cdr curr) (+ i 1)))))
       (ffi-set! (ptr+ ,ptr (* ,len ,psize)) 'pointer ())
       (dynamic-wind
         (lambda () #f)
         (lambda ()
           (let ((,var (tptr 'pointer ,ptr)))
             ,@body))
         (lambda ()
           (for-each free ,ptrs)
           (free ,ptr))))))

;; --- Capturing Engine ---
(c-import c-fflush  libc-basic "fflush"  int     (pointer))
(c-import c-dup     libc-basic "dup"     int     (int))
(c-import c-dup2    libc-basic "dup2"    int     (int int))
(c-import c-close   libc-basic "close"   int     (int))
(c-import c-tmpfile libc-basic "tmpfile" pointer ())
(c-import c-fileno  libc-basic "fileno"  int     (pointer))
(c-import c-rewind  libc-basic "rewind"  void    (pointer))
(c-import c-fclose  libc-basic "fclose"  int     (pointer))
(c-import c-fgetc   libc-basic "fgetc"   int     (pointer))

(define-macro (capture . body)
  (let ((saved (gensym))
        (tmp (gensym))
        (fd (gensym))
        (str (gensym))
        (char (gensym))
        (chars (gensym)))
    `(begin
       (c-fflush ())
       (let* ((,saved (c-dup 1))
              (,tmp (c-tmpfile))
              (,fd (c-fileno ,tmp)))
         (c-dup2 ,fd 1)
         (dynamic-wind
           (lambda () #f)
           (lambda ()
             ,@body)
           (lambda ()
             (c-fflush ())
             (c-dup2 ,saved 1)
             (c-close ,saved)))
         (c-rewind ,tmp)
         (let* ((,chars '()))
           (let loop ((,char (c-fgetc ,tmp)))
             (if (not (= ,char -1))
                 (begin
                   (set! ,chars (cons (integer->char ,char) ,chars))
                   (loop (c-fgetc ,tmp)))))
           (c-fclose ,tmp)
           (list->string (reverse ,chars)))))))

;; --- Common Helper Functions ---
(define (null-ptr? x)
  (let ((ptr (if (tptr? x) (tptr-ptr x) x)))
    (or (null? ptr)
        (eq? ptr 0)
        (and (c-pointer? ptr) (= (c-pointer->integer ptr) 0)))))

(define (null-ptr)
  ())

(define (c-string-from-ptr x)
  (let ((ptr (if (tptr? x) (tptr-ptr x) x)))
    (if (null-ptr? ptr)
        ""
        (let ((chars '()))
          (let loop ((i 0))
            (let ((char-val (ffi-deref (ptr+ ptr i) 'char)))
              (if (not (= char-val 0))
                  (begin
                    (set! chars (cons (integer->char char-val) chars))
                    (loop (+ i 1))))))
          (list->string (reverse chars))))))

(define (c-string-array->list tp)
  (let* ((ptr (if (tptr? tp) (tptr-ptr tp) tp))
         (psize (c-size 'pointer)))
    (if (null-ptr? ptr)
        '()
        (let loop ((i 0) (res '()))
          (let ((sptr (ffi-deref (ptr+ ptr (* i psize)) 'pointer)))
            (if (null-ptr? sptr)
                (reverse res)
                (loop (+ i 1) (cons (c-string-from-ptr sptr) res))))))))

(define (c-cast tp target-type)
  (if (tptr? tp)
      (tptr target-type (tptr-ptr tp))
      (tptr target-type tp)))
